
% SC. short for SHIMMER_CALIBRATION_
% SC.VER.HW                      = 0;% DEVICE_VER
% SC.VER.FW_ID_L                 = 1;
% SC.VER.FW_ID_H                 = 2;
% SC.VER.FW_MAJOR_L              = 3;
% SC.VER.FW_MAJOR_H              = 4;
% SC.VER.FW_MINOR                = 5;
% SC.VER.FW_REL                  = 6;

SC.OFFSET.LENGTH_L             0
SC.OFFSET.LENGTH_H             1
SC.OFFSET.VER_HW_ID_L          2
SC.OFFSET.VER_HW_ID_H          3
SC.OFFSET.VER_FW_ID_L          4
SC.OFFSET.VER_FW_ID_H          5
SC.OFFSET.VER_FW_MAJOR_L       6
SC.OFFSET.VER_FW_MAJOR_H       7
SC.OFFSET.VER_FW_MINOR_L       8
SC.OFFSET.VER_FW_INTER_L       9

SC.OFFSET.SENSOR_ID_L          = 0;
SC.OFFSET.SENSOR_ID_H          = 1;
SC.OFFSET.SENSOR_RANGE         = 2;
SC.OFFSET.SENSOR_LENGTH        = 3;
SC.OFFSET.SENSOR_TIMESTAMP     = 4;
SC.OFFSET.SENSOR_DATA          = 12;

SC.SENSOR_ANALOG_ACCEL         = 2;
SC.SENSOR_MPU9150_GYRO         = 30;
SC.SENSOR_LSM303DLHC_ACCEL     = 31;
SC.SENSOR_LSM303DLHC_MAG       = 32;
SC.SENSOR_BMP180_PRESSURE      = 36;
SC.SENSOR_HOST_ECG             = 100;

% Analogue Accel Range
SC.SENSOR_RANGE_ANALOG_ACCEL               = 0;
SC.SENSOR_RANGE_MAX_ANALOG_ACCEL           = 1;
SC.SENSOR_RANGE_SIZE_ANALOG_ACCEL          = 21;
% LSM303DLHC Accel Range
SC.SENSOR_RANGE_LSM303DLHC_ACCEL_2G        = 0;
SC.SENSOR_RANGE_LSM303DLHC_ACCEL_4G        = 1;
SC.SENSOR_RANGE_LSM303DLHC_ACCEL_8G        = 2;
SC.SENSOR_RANGE_LSM303DLHC_ACCEL_16G       = 3;
SC.SENSOR_RANGE_MAX_LSM303DLHC_ACCEL       = 4;
SC.SENSOR_RANGE_SIZE_LSM303DLHC_ACCEL      = 21;
% LSM303DLHC Mag gain
SC.SENSOR_RANGE_LSM303DLHC_MAG_1_3G        = 1; % +/-1.3 Gauss
SC.SENSOR_RANGE_LSM303DLHC_MAG_1_9G        = 2; % +/-1.9 Gauss
SC.SENSOR_RANGE_LSM303DLHC_MAG_2_5G        = 3; % +/-2.5 Gauss
SC.SENSOR_RANGE_LSM303DLHC_MAG_4_0G        = 4; % +/-4.0 Gauss
SC.SENSOR_RANGE_LSM303DLHC_MAG_4_7G        = 5; % +/-4.7 Gauss
SC.SENSOR_RANGE_LSM303DLHC_MAG_5_6G        = 6; % +/-5.6 Gauss
SC.SENSOR_RANGE_LSM303DLHC_MAG_8_1G        = 7; % +/-8.1 Gauss
SC.SENSOR_RANGE_MAX_LSM303DLHC_MAG         = 7;
SC.SENSOR_RANGE_SIZE_LSM303DLHC_MAG        = 21;
% MPU9x50 Gyro range
SC.SENSOR_RANGE_MPU9250_GYRO_250DPS        = 0; % +/-250 dps
SC.SENSOR_RANGE_MPU9250_GYRO_500DPS        = 1; % +/-500 dps
SC.SENSOR_RANGE_MPU9250_GYRO_1000DPS       = 2; % +/-1000 dps
SC.SENSOR_RANGE_MPU9250_GYRO_2000DPS       = 3; % +/-2000 dps
SC.SENSOR_RANGE_MAX_MPU9250_GYRO           = 4;
SC.SENSOR_RANGE_SIZE_MPU9250_GYRO          = 21;
% BMP180 Temperature/Pressure Range
SC.SENSOR_RANGE_BMP180                     = 0;
SC.SENSOR_RANGE_MAX_BMP180                 = 1;
SC.SENSOR_RANGE_SIZE_BMP180                = 22;
